name: Python SDK Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Debug Information
      run: |
        echo "Running on branch: $GITHUB_REF"
        echo "Event name: $GITHUB_EVENT_NAME"
        echo "Workflow triggered by: $GITHUB_ACTOR"
    
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        pytest ./tests -v
